DeepinWebApp/app/routes/aboutus.py
from flask import Blueprint, render_template

about_bp = Blueprint('about', __name__)

@about_bp.route('/aboutus')
def about():
    return render_template('aboutus.html')

DeepinWebApp/app/routes/admixture.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from app.forms import AdmixtureAnalysisForm

admixture = Blueprint('admixture', __name__)

@admixture.route('/admixture', methods=['GET', 'POST'])
def admixture_analysis():
    form = AdmixtureAnalysisForm()
    
    if form.validate_on_submit():
        
        selected_populations = form.populations.data
        num_ancestral_pops = form.num_ancestral_pops.data
        
        flash('Analysis submitted successfully.', 'success')
        return redirect(url_for('admixture.admixture_analysis'))
    
    return render_template('admixture.html', form=form) 

DeepinWebApp/app/routes/clustering.py
from flask import Blueprint, request, render_template
from flask_sqlalchemy import SQLAlchemy
from app.forms import ClusteringAnalysisForm
from app.models import SampleTable, FinalAnalysisResults
import pandas as pd
import matplotlib.pyplot as plt
import base64
import io
from sklearn.decomposition import PCA

clustering = Blueprint('clustering', __name__)
db = SQLAlchemy()

@clustering.route('/clustering', methods=['GET', 'POST'])
def clustering_analysis():
    form = ClusteringAnalysisForm()

    if form.validate_on_submit():
        selected_populations = form.populations.data
        selected_superpopulations = form.superpopulations.data

        # Adjust your query as necessary, filtering by selected populations and superpopulations if provided
        query = db.session.query(SampleTable.POP, SampleTable.SUPER_POP, 
                                 FinalAnalysisResults.PCA1, FinalAnalysisResults.PCA2)\
                          .join(FinalAnalysisResults, SampleTable.SAMPLE_ID == FinalAnalysisResults.SAMPLE_ID)

        if selected_populations:
            query = query.filter(SampleTable.POP.in_(selected_populations))
        if selected_superpopulations:
            query = query.filter(SampleTable.SUPER_POP.in_(selected_superpopulations))

        df = pd.read_sql(query.statement, db.engine)

        # Perform PCA and plotting if data is not empty
        if not df.empty:
            pca = PCA(n_components=2)
            pca_result = pca.fit_transform(df[['PCA1', 'PCA2']])
            
            plt.figure(figsize=(10, 7))
            plt.scatter(pca_result[:, 0], pca_result[:, 1], alpha=0.7)
            plt.title('PCA Analysis')
            plt.xlabel('Principal Component 1')
            plt.ylabel('Principal Component 2')
            
            # Convert plot to PNG image
            img = io.BytesIO()
            plt.savefig(img, format='png')
            img.seek(0)
            plot_url = base64.b64encode(img.getvalue()).decode('utf8')
        else:
            plot_url = None

        return render_template('clustering_results.html', form=form, plot_url=plot_url)

    return render_template('clustering.html', form=form)

DeepinWebApp/app/routes/snp_search.py
from flask import Blueprint, render_template
from app.forms import SNPSearchForm

snp_info_bp = Blueprint('snp_info', __name__)

@snp_info_bp.route('/snp_search', methods=['GET', 'POST'])
def snp_search():
    form = SNPSearchForm()
    results = None 
    error = None  

    if form.validate_on_submit():
        search_option = form.search_option.data
        selected_populations = form.populations.data

    return render_template('snp_search.html', form=form, results=results, error=error)

DeepinWebApp/app/templates/aboutus.html
{% extends 'base.html' %}

{% block content %}
<div class="about-section">
    <h1>About Us</h1>
    <p>We are a team of Master's students at Queen Mary University of London, working on population genetics and bioinformatics. Our goal is to provide tools and resources for analysing genetic data in the context of human population genetics. We believe that open and accessible tools are essential for scientific progress and we strive to make our work available to the wider scientific community.</p>
    <p>If you have any questions or feedback, please don't hesitate to contact us.</p>
    <p>Email: <a href="mailto:bt23844@qmul.ac.uk">bt23844@qmul.ac.uk</a></p>
</div>
{% endblock %}

DeepinWebApp/app/templates/admixture.html
{% extends 'base.html' %}

{% block content %}

<div class="admixture-analysis-banner">
    <!-- Banner content here -->
</div>

<h2>Admixture Analysis</h2>
<form method="post" id="admixture-form">
    {{ form.hidden_tag() }}

    <!-- Superpopulations and their populations -->
    {% for superpop_code, populations in form.populations_by_superpopulation().items() %}
    <div class="form-group">
        <!-- Superpopulation Header -->
        <div class="collapsible-header" data-toggle="collapse" data-target="#collapse{{ superpop_code }}">
         Select {{ form.superpopulations.choices|selectattr('0', 'equalto', superpop_code)|map(attribute='1')|first }} Populations
         <i class="fa fa-chevron-down collapsible-arrow"></i>
        </div>
        
        <!-- Populations for this Superpopulation -->
        <div id="collapse{{ superpop_code }}" class="collapse collapsible-content">
            <div class="card card-body">
                {% for value, pop_label in populations %}
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="populations" value="{{ value }}" id="{{ value }}">
                    <label class="form-check-label" for="{{ value }}">
                        {{ pop_label }}
                    </label>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="form-group">
        {{ form.num_ancestral_pops.label }}
        {{ form.num_ancestral_pops(class="form-control", min=1) }}
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">submit for analysis</button>
    </div>
</form>

{% endblock %}

DeepinWebApp/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous">
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <title>Genetic Analysis App</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Deepin Genetic Analysis Hub</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="/">Home</a>
                    <a class="nav-item nav-link" href="/clustering">Clustering Analysis</a>
                    <a class="nav-item nav-link" href="/admixture">Admixture Analysis</a>
                    <a class="nav-item nav-link" href="/snp_search">SNP Search</a>
                    <a class="nav-item nav-link" href="/aboutus">About Us</a>
                </div>
            </div>
        </nav>
    </header>

    <!-- Conditional banner image based on the endpoint -->
    {% if request.endpoint == 'main.home' %}
    <div class="banner-image">
        <img src="{{ url_for('static', filename='/images/banner.png') }}" alt="Home Banner" class="img-fluid">
    </div>
    {% elif request.endpoint == 'main.clustering' %}
    <div class="banner-image">
        <img src="{{ url_for('static', filename='/images/Deepin genetics hub section banners/clustering_analysis_banner.png') }}" alt="Clustering Analysis Banner" class="img-fluid">
    </div>
    {% elif request.endpoint == 'main.admixture' %}
    <div class="banner-image">
        <img src="{{ url_for('static', filename='/images/Deepin genetics hub section banners/admixture_analysis_banner.png') }}" alt="Admixture Analysis Banner" class="img-fluid">
    </div>
    {% elif request.endpoint == 'main.snp_search' %}
    <div class="banner-image">
        <img src="{{ url_for('static', filename='/images/Deepin genetics hub section banners/snp_search_banner.png') }}" alt="SNP Search Banner" class="img-fluid">
    </div>
    {% elif request.endpoint == 'main.aboutus' %}
    <div class="banner-image">
        <img src="{{ url_for('static', filename='images/Deepin genetics hub section banners/about_banner.png') }}" alt="About Us Banner" class="img-fluid">
    </div>
    {% endif %}

    <!-- Main content container -->
    <div class="container main-content-container mt-4">
        <main role="main">
            {% block content %}
            
            {% endblock %}
        </main>
    </div>

    <!-- Bootstrap and jQuery scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    <script>
    function displaySummary() {
        let formData = new FormData(document.getElementById('snpSearchForm'));
        let summary = '';
        
        for (let [key, value] of formData.entries()) {
            if (value) {
                summary += `<p><strong>${key}:</strong> ${value}</p>`;
            }
        }
        
        document.getElementById('summaryContent').innerHTML = summary;
    }
</script>

</body>
</html>

DeepinWebApp/app/templates/clustering.html
{% extends 'base.html' %}

{% block content %}

<div class="clustering-analysis-banner"></div>

<h2>Clustering Analysis</h2>
<form method="post">
    {{ form.hidden_tag() }}

    {% for superpop_code, populations in form.populations_by_superpopulation().items() %}
    <!-- Collapsible for Superpopulations -->
    <div class="form-group">
        <div id="collapse{{ superpop_code }}Header" class="collapsible-header" data-toggle="collapse" data-target="#collapse{{ superpop_code }}">
            Select {{ form.superpopulations.choices|selectattr('0', 'equalto', superpop_code)|map(attribute='1')|first }} Populations
            <i class="fa fa-chevron-down collapsible-arrow"></i>
        </div>
        <div id="collapse{{ superpop_code }}" class="collapse collapsible-content">
            <div class="card card-body">
                {% for value, pop_label in populations %}
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="populations" value="{{ value }}" id="{{ value }}">
                    <label class="form-check-label" for="{{ value }}">
                        {{ pop_label }}
                    </label>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endfor %}
    
    <!-- Analysis Method Radio Buttons -->
    <div class="form-group">
        {{ form.analysis_method.label }}
        {% for radio in form.analysis_method %}
            <div class="form-check">
                {{ radio(class="form-check-input") }} {{ radio.label(class="form-check-label") }}
            </div>
        {% endfor %}
    </div>

    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>

{% endblock %}

DeepinWebApp/app/templates/clustering_results.html
{% extends "base.html" %}
{% block content %}
    <h2>PCA Analysis Results</h2>
    {% if plot_url %}
        <img src="data:image/png;base64,{{ plot_url }}" alt="PCA Plot">
    {% else %}
        <p>No data available to display.</p>
    {% endif %}
    <a href="{{ url_for('clustering.clustering_analysis') }}" class="btn btn-secondary">Back</a>
{% endblock %}

DeepinWebApp/app/templates/index.html
{% extends 'base.html' %} 

{% block content %}


  <div class="analysis-options">
  <label for="analysis-select">Choose an analysis:</label>
  <select id="analysis-select" onchange="location = this.value;">
    <option value="">Select an option...</option>
    <option value="{{ url_for('main.clustering') }}">Cluster Analysis</option>
    <option value="{{ url_for('main.admixture') }}">Admixture Analysis</option>
    <option value="{{ url_for('main.snp_search') }}">SNP Search</option>
  </select>
</div>
{% endblock %}

DeepinWebApp/app/templates/snp_search.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>SNP Search</h2>
    <form method="post" id="snpSearchForm">
        {{ form.hidden_tag() }}

        <!-- Search Option Radio Buttons -->
        <div class="form-group">
            {{ form.search_option.label }}
            {% for option in form.search_option %}
            <div class="form-check">
                {{ option(class="form-check-input") }} {{ option.label(class="form-check-label") }}
            </div>
            {% endfor %}
        </div>

        <!-- Dynamic Input Fields based on the selected search option -->
        <div class="form-group" id="snpIdsInput" style="display: none;">
            {{ form.snp_ids.label }}
            {{ form.snp_ids(class="form-control") }}
        </div>
        <div class="form-group" id="chromosomePositionInput" style="display: none;">
            {{ form.chromosome.label }}
            {{ form.chromosome(class="form-control") }}
            {{ form.position.label }}
            {{ form.position(class="form-control") }}
        </div>
        <div class="form-group" id="geneNamesInput" style="display: none;">
            {{ form.gene_names.label }}
            {{ form.gene_names(class="form-control") }}
        </div>

        <!-- Collapsible for Superpopulations and Populations, using full names for superpopulations -->
        {% for superpop_code, populations in form.populations_by_superpopulation().items() %}
        <div class="form-group">
            <div id="collapse{{ superpop_code }}Header" class="collapsible-header" data-toggle="collapse" data-target="#collapse{{ superpop_code }}">
                Select {{ form.superpopulations.choices|selectattr('0', 'equalto', superpop_code)|map(attribute='1')|first }} Populations
                <i class="fa fa-chevron-down collapsible-arrow"></i>
            </div>
            <div id="collapse{{ superpop_code }}" class="collapse collapsible-content">
                <div class="card card-body">
                    {% for value, pop_label in populations %}
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="populations" value="{{ value }}" id="{{ value }}">
                        <label class="form-check-label" for="{{ value }}">
                            {{ pop_label }}
                        </label>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">{{ form.submit.label }}</button>
    </form>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
    const searchOptionRadios = document.getElementsByName("search_option");
    const snpIdsInput = document.getElementById("snpIdsInput");
    const geneNamesInput = document.getElementById("geneNamesInput");
    const chromosomePositionInput = document.getElementById("chromosomePositionInput");

    function toggleInputFields() {
        snpIdsInput.style.display = "none";
        geneNamesInput.style.display = "none";
        chromosomePositionInput.style.display = "none";

        if (searchOptionRadios[0].checked) {
            snpIdsInput.style.display = "block";
        } else if (searchOptionRadios[1].checked) {
            geneNamesInput.style.display = "block";
        } else if (searchOptionRadios[2].checked) {
            chromosomePositionInput.style.display = "block";
        }
    }

    searchOptionRadios.forEach(radio => radio.addEventListener("change", toggleInputFields));
    toggleInputFields(); // Call this function initially to set the correct display state based on the pre-selected search option.
});
</script>
{% endblock %}